language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://rodolfouriel.pactflow.io
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "cuchexXwtOe8Nkhevagx26Mv5hYbLIwhuYHnh/z1P+BM8gQrC3/oVGS/maxj194XhsRn0yhSOm9fpo98FuGTuJ16Xcz5LxKsfot1uj+JdTcq3tqvqGDaPp8XUhQapNpMFjho/xeqsW8oqmZNB1f8MwpbLbpaeViacIb+B8sveBW/q25UhEXm7SfIjsQcVT8cETHRbkpIaJkIw4WrWso0em3VUVhljT1DQ4PCVbMu/Y3150AhucFJrc3Az+Nl0nNL756AmPUcdDiObjl2oYmOzq/GAUUKK4vIX6SKBabhEdaBi5xR7VOcCOPDxjZptYvBLbIikhKotCgzNRb9XjTCfUIvVAR3p/NnaFr9Cj69+48f5dP7iaFvxwD/7Ke7U73nnZpfeww3+JNq/ZWzdCGh/fbJ/zC9xLKNRqIYulWDQQXJz22Mp6n1RCW6SNtVHfqA+ilTYb1ezGX66SlqrR4stdT4DBqAs7YrII7tfJVO/8UKduPhj1GqY2zwMofhQhMi2cEu/GR2QJ4+N8voiHXegVFS8yEnHIG9xd5CAVsKJzVnt4hqW3A5utTBRcnj3AIzOpOGGb2NMMTcZATqVsfXahmxrsluhhbv+uNxhBzFQYz3WqOLSANVoCwpKZRl0ygsEE6U4JMUgNge12uMoBIg2+UqFc2FxI/VFYEfS4SNYVE="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
