language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://rodolfouriel.pactflow.io
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "PzXBr79HkRG/leJFu9mv/UIK/2QIrjFsu7Qxo6w0VOcMct7lk8MX7RlZW17bouTVubwN29epoPZm3a5peutuc/WTHRsbBJiDql0ulGhNhMunJH3gbRlaYFQ/rFYR6MyjgDs0rEZ8jalUgdVcZ+hdIwUdhDOUhEiPgipx+zU0YDtr7NQ9frOJEwIqGnRluq+0+siTiKQ94Lve86VM9QwrymomLHx1gRaeTrCFkHinaR3QNQrsfd9fD+RxiTolYOso5iYWDpMq/2WXeRdvMytiH4hnqa5mR1Df73Oms4wV99APoTwhwafSv9vmOX14JghFv0f2yzbSYuNcbfjffpxPJuTbt+nzUj4o6ghXJ8eXWd76/qOQSBtXaOTtrMlyeOPa6msENN9/Cl7ccfb8a7qutWc+6IwHtjrpaiGshFbQ4U3xAHXH+OswfVBfh52W6lyLluLR4smDw4UXDitEyktmTwk2OxP2bptnVI4zavcaJyAjxX0Jx2KzAuiVonOcNZeTyFhcn3cVjfFxOW4QHp5XU9e6OykZ7f1lapOFYyeqIfXIxO+30GpV1pjJAsLEjE8HuJjsNGZWDd/nBEaUBSbJRq7s+TnWEBTvTUwgNpVbYz92oHQXgKGAYQIE3bcQ6/rr0j8dcwgoCw71gfQ7+hy7kh9abEsKTMgvEF7N1YlkoMs="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
